### PR TITLE
Updated function introspection

### PR DESCRIPTION
**Pull request by sbly**
Switched from "getarcspec" to "getfullargspec" which e.g. allows function annotations.

### CODE REVIEW

**Comment by sbly** [comment]
LGTM. Good job me!

**Comment by ysimonson** [comment]
Looks like tests are failing. You can test locally with `tox`.

**Comment by sbly** [comment]
Yeah, it's some Python 2.6 funkiness. I'll look into it more after I've quashed the more pressing bugs

**Comment by sbly** [comment]
@ysimonson This is working now

**Pull request merged**
